var listaCursos=[
{"codigo":1, nombre:"1SRMA"},
{"codigo":2, nombre:"2SMRA"},
{"codigo":3, nombre:"1COM"},
{"codigo":4, nombre:"2COM"},
{"codigo":5, nombre:"1DAW"},
{"codigo":6, nombre:"2DAW"},
{"codigo":7, nombre:"1ASIR"},
{"codigo":8, nombre:"2ASIR"},
{"codigo":9, nombre:"1DAM"},
{"codigo":10, nombre:"2DAM"}
];
var listaAlumnos=[
{"codigo":1, "nombre":"PEDRO", 
"apellidos":"MARMOL GARCIA","direccion":"C/Avefria 23",
"foto":"foto1.gif","edad":33, "codigo_curso":1,
"modalidad":"Presencial","nota":0},
{"codigo":2, "nombre":"PABLO", 
"apellidos":"MARMOL GARCIA","direccion":"C/Avefria 23",
"foto":"foto2.gif","edad":33, "codigo_curso":1,
"modalidad":"Presencial","nota":0},
{"codigo":3, "nombre":"PATRICIA", 
"apellidos":"GOMEZ BORRERO","direccion":"C/Avefria 23",
"foto":"foto3.gif","edad":33, "codigo_curso":1,
"modalidad":"Presencial","nota":0},
{"codigo":4, "nombre":"PEDRO", 
"apellidos":"GARCIA GOMEZ","direccion":"C/Avefria 23",
"foto":"foto4.gif","edad":33, "codigo_curso":1,
"modalidad":"Presencial","nota":0},
{"codigo":5, "nombre":"JUAN", 
"apellidos":"JIMENEZ GARCIA","direccion":"C/Avefria 23",
"foto":"foto5.gif","edad":33, "codigo_curso":1,
"modalidad":"Presencial","nota":0},
{"codigo":6, "nombre":"JAVIER", 
"apellidos":"LOPEZ ALEGRIA","direccion":"C/Avefria 23",
"foto":"foto6.gif","edad":33, "codigo_curso":1,
"modalidad":"Presencial","nota":0},
{"codigo":7, "nombre":"JOSE", 
"apellidos":"PARADA GARCIA","direccion":"C/Avefria 23",
"foto":"foto7.gif","edad":33, "codigo_curso":1,
"modalidad":"Presencial","nota":0},
{"codigo":8, "nombre":"JAIME", 
"apellidos":"DEL BURGO GARCIA","direccion":"C/Avefria 23",
"foto":"foto8.gif","edad":33, "codigo_curso":1,
"modalidad":"Presencial","nota":0},
{"codigo":9, "nombre":"JULIA", 
"apellidos":"AARON LOPEZ","direccion":"C/Avefria 23",
"foto":"foto9.gif","edad":33, "codigo_curso":1,
"modalidad":"Presencial","nota":0},
{"codigo":10, "nombre":"PATRICIA", 
"apellidos":"BLANCO LOPEZ","direccion":"C/Avefria 23",
"foto":"foto10.gif","edad":33, "codigo_curso":1,
"modalidad":"Presencial","nota":0},
{"codigo":21, "nombre":"PEDRO", 
"apellidos":"MARMOL GARCIA","direccion":"C/Avefria 23",
"foto":"foto1.gif","edad":33, "codigo_curso":2,
"modalidad":"Presencial","nota":0},
{"codigo":22, "nombre":"PABLO", 
"apellidos":"MARMOL GARCIA","direccion":"C/Avefria 23",
"foto":"foto2.gif","edad":33, "codigo_curso":2,
"modalidad":"Presencial","nota":0},
{"codigo":23, "nombre":"PATRICIA", 
"apellidos":"GOMEZ BORRERO","direccion":"C/Avefria 23",
"foto":"foto3.gif","edad":33, "codigo_curso":2,
"modalidad":"Presencial","nota":0},
{"codigo":24, "nombre":"PEDRO", 
"apellidos":"GARCIA GOMEZ","direccion":"C/Avefria 23",
"foto":"foto4.gif","edad":33, "codigo_curso":2,
"modalidad":"Presencial","nota":0},
{"codigo":25, "nombre":"JUAN", 
"apellidos":"JIMENEZ GARCIA","direccion":"C/Avefria 23",
"foto":"foto5.gif","edad":33, "codigo_curso":2,
"modalidad":"Presencial","nota":0},
{"codigo":26, "nombre":"JAVIER", 
"apellidos":"LOPEZ ALEGRIA","direccion":"C/Avefria 23",
"foto":"foto6.gif","edad":33, "codigo_curso":2,
"modalidad":"Presencial","nota":0},
{"codigo":27, "nombre":"JOSE", 
"apellidos":"PARADA GARCIA","direccion":"C/Avefria 23",
"foto":"foto7.gif","edad":33, "codigo_curso":2,
"modalidad":"Presencial","nota":0},
{"codigo":28, "nombre":"JAIME", 
"apellidos":"DEL BURGO GARCIA","direccion":"C/Avefria 23",
"foto":"foto8.gif","edad":33, "codigo_curso":2,
"modalidad":"Presencial","nota":0},
{"codigo":29, "nombre":"JULIA", 
"apellidos":"AARON LOPEZ","direccion":"C/Avefria 23",
"foto":"foto9.gif","edad":33, "codigo_curso":2,
"modalidad":"Presencial","nota":0},
{"codigo":30, "nombre":"PATRICIA", 
"apellidos":"BLANCO LOPEZ","direccion":"C/Avefria 23",
"foto":"foto1.gif","edad":33, "codigo_curso":2,
"modalidad":"Presencial","nota":0},
{"codigo":41, "nombre":"PEDRO", 
"apellidos":"MARMOL GARCIA","direccion":"C/Avefria 23",
"foto":"foto2.gif","edad":33, "codigo_curso":3,
"modalidad":"Presencial","nota":0},
{"codigo":42, "nombre":"PABLO", 
"apellidos":"MARMOL GARCIA","direccion":"C/Avefria 23",
"foto":"foto1.gif","edad":33, "codigo_curso":3,
"modalidad":"Presencial","nota":0},
{"codigo":43, "nombre":"PATRICIA", 
"apellidos":"GOMEZ BORRERO","direccion":"C/Avefria 23",
"foto":"foto3.gif","edad":33, "codigo_curso":3,
"modalidad":"Presencial","nota":0},
{"codigo":44, "nombre":"PEDRO", 
"apellidos":"GARCIA GOMEZ","direccion":"C/Avefria 23",
"foto":"foto4.gif","edad":33, "codigo_curso":3,
"modalidad":"Presencial","nota":0},
{"codigo":45, "nombre":"JUAN", 
"apellidos":"JIMENEZ GARCIA","direccion":"C/Avefria 23",
"foto":"foto5.gif","edad":33, "codigo_curso":3,
"modalidad":"Presencial","nota":0},
{"codigo":46, "nombre":"JAVIER", 
"apellidos":"LOPEZ ALEGRIA","direccion":"C/Avefria 23",
"foto":"foto6.gif","edad":33, "codigo_curso":3,
"modalidad":"Presencial","nota":0},
{"codigo":47, "nombre":"JOSE", 
"apellidos":"PARADA GARCIA","direccion":"C/Avefria 23",
"foto":"foto7.gif","edad":33, "codigo_curso":3,
"modalidad":"Presencial","nota":0},
{"codigo":48, "nombre":"JAIME", 
"apellidos":"DEL BURGO GARCIA","direccion":"C/Avefria 23",
"foto":"foto8.gif","edad":33, "codigo_curso":3,
"modalidad":"Presencial","nota":0},
{"codigo":49, "nombre":"JULIA", 
"apellidos":"AARON LOPEZ","direccion":"C/Avefria 23",
"foto":"foto9.gif","edad":33, "codigo_curso":3,
"modalidad":"Presencial","nota":0},
{"codigo":50, "nombre":"PATRICIA", 
"apellidos":"BLANCO LOPEZ","direccion":"C/Avefria 23",
"foto":"foto10.gif","edad":33, "codigo_curso":3,
"modalidad":"Presencial","nota":0},
{"codigo":61, "nombre":"PEDRO", 
"apellidos":"MARMOL GARCIA","direccion":"C/Avefria 23",
"foto":"foto1.gif","edad":33, "codigo_curso":2,
"modalidad":"Dual","nota":0},
{"codigo":62, "nombre":"PABLO", 
"apellidos":"MARMOL GARCIA","direccion":"C/Avefria 23",
"foto":"foto2.gif","edad":33, "codigo_curso":2,
"modalidad":"Dual","nota":0},
{"codigo":63, "nombre":"PATRICIA", 
"apellidos":"GOMEZ BORRERO","direccion":"C/Avefria 23",
"foto":"foto3.gif","edad":33, "codigo_curso":2,
"modalidad":"Dual","nota":0},
{"codigo":64, "nombre":"PEDRO", 
"apellidos":"GARCIA GOMEZ","direccion":"C/Avefria 23",
"foto":"foto4.gif","edad":33, "codigo_curso":2,
"modalidad":"Dual","nota":0},
{"codigo":65, "nombre":"JUAN", 
"apellidos":"JIMENEZ GARCIA","direccion":"C/Avefria 23",
"foto":"foto5.gif","edad":33, "codigo_curso":2,
"modalidad":"Dual","nota":0},
{"codigo":26, "nombre":"JAVIER", 
"apellidos":"LOPEZ ALEGRIA","direccion":"C/Avefria 23",
"foto":"foto6.gif","edad":33, "codigo_curso":2,
"modalidad":"Dual","nota":0},
{"codigo":27, "nombre":"JOSE", 
"apellidos":"PARADA GARCIA","direccion":"C/Avefria 23",
"foto":"foto7.gif","edad":33, "codigo_curso":2,
"modalidad":"Dual","nota":0},
{"codigo":68, "nombre":"JAIME", 
"apellidos":"DEL BURGO GARCIA","direccion":"C/Avefria 23",
"foto":"foto8.gif","edad":33, "codigo_curso":2,
"modalidad":"Dual","nota":0},
{"codigo":69, "nombre":"JULIA", 
"apellidos":"AARON LOPEZ","direccion":"C/Avefria 23",
"foto":"foto9.gif","edad":33, "codigo_curso":2,
"modalidad":"Dual","nota":0},
{"codigo":70, "nombre":"PATRICIA", 
"apellidos":"BLANCO LOPEZ","direccion":"C/Avefria 23",
"foto":"foto10.gif","edad":33, "codigo_curso":2,
"modalidad":"Dual","nota":0}
];


